/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

'use strict';

import { suite, test } from 'node:test';
import * as assert from 'node:assert';
import { Hover, MarkedString, TextDocument, getCSSLanguageService, getLESSLanguageService, getSCSSLanguageService } from '../../cssLanguageService.js';
import { HoverSettings } from '../../cssLanguageTypes.js';
import { BaselineImages } from '../../languageFacts/facts.js';

function assertHover(value: string, expected: Hover, languageId = 'css', hoverSettings?: HoverSettings): void {
	let offset = value.indexOf('|');
	value = value.substr(0, offset) + value.substr(offset + 1);
	const ls = languageId === 'css' ? getCSSLanguageService() : languageId === 'less' ? getLESSLanguageService() : getSCSSLanguageService();

	const document = TextDocument.create(`test://foo/bar.${languageId}`, languageId, 1, value);
	const hoverResult = ls.doHover(document, document.positionAt(offset), ls.parseStylesheet(document), hoverSettings);
	assert.ok(hoverResult);

	if (hoverResult!.range && expected.range) {
		assert.equal(hoverResult!.range, expected.range);
	}
	assert.deepEqual(hoverResult!.contents, expected.contents);
}

suite('CSS Hover', () => {
	test('basic', () => {
		assertHover('.test { |color: blue; }', {
			contents: {
				kind: 'markdown',
				value:
					`Sets the color of an element's text\n\n![Baseline icon](${BaselineImages.BASELINE_HIGH}) _Widely available across major browsers (Baseline since 2015)_\n\nSyntax: &lt;color&gt;\n\n[MDN Reference](https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/color)`,
			},
		});
		assertHover(
			'.test { |color: blue; }',
			{
				contents: {
					kind: 'markdown',
					value: '[MDN Reference](https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/color)',
				},
			},
			undefined,
			{ documentation: false },
		);
		assertHover(
			'.test { |color: blue; }',
			{
				contents: {
					kind: 'markdown',
					value: `Sets the color of an element's text\n\n![Baseline icon](${BaselineImages.BASELINE_HIGH}) _Widely available across major browsers (Baseline since 2015)_\n\nSyntax: &lt;color&gt;`,
				},
			},
			undefined,
			{ references: false },
		);

		/**
		 * Reenable after converting specificity to use MarkupContent
		 */

		// assertHover('.test:h|over { color: blue; }', {
		// 	contents: `Applies while the user designates an element with a pointing device, but does not necessarily activate it. For example, a visual user agent could apply this pseudo-class when the cursor (mouse pointer) hovers over a box generated by the element.`
		// });

		// assertHover('.test::a|fter { color: blue; }', {
		// 	contents: `Represents a styleable child pseudo-element immediately after the originating element’s actual content.`
		// });
	});

	test('specificity', () => {
		assertHover('.|foo {}', {
			contents: [{ language: 'html', value: '<element class="foo">' }, '[Selector Specificity](https://developer.mozilla.org/docs/Web/CSS/Specificity): (0, 1, 0)'],
		});
	});

	test('nested', () => {
		assertHover(
			'div { d|iv {} }',
			{
				contents: [{ language: 'html', value: '<div>\n  …\n    <div>' }, '[Selector Specificity](https://developer.mozilla.org/docs/Web/CSS/Specificity): (0, 0, 2)'],
			},
			'css',
		);
		assertHover(
			'.foo{ .bar{ @media only screen{ .|bar{ } } } }',
			{
				contents: [
					{
						language: 'html',
						value: '@media only screen\n<element class="foo">\n  …\n    <element class="bar">\n      …\n        <element class="bar">',
					},
					'[Selector Specificity](https://developer.mozilla.org/docs/Web/CSS/Specificity): (0, 3, 0)',
				],
			},
			'css',
		);

		assertHover(
			'@scope (.foo) to (.bar) { .|baz{ } }',
			{
				contents: [
					{
						language: 'html',
						value: '@scope .foo → .bar\n<element class="baz">',
					},
					'[Selector Specificity](https://developer.mozilla.org/docs/Web/CSS/Specificity): (0, 1, 0)',
				],
			},
			'css',
		);

		assertHover(
			'@scope (.from) to (.to) { .foo { @media print { .bar { @media only screen{ .|bar{ } } } } } }',
			{
				contents: [
					{
						language: 'html',
						value: '@scope .from → .to\n@media print\n@media only screen\n<element class="foo">\n  …\n    <element class="bar">\n      …\n        <element class="bar">',
					},
					'[Selector Specificity](https://developer.mozilla.org/docs/Web/CSS/Specificity): (0, 3, 0)',
				],
			},
			'css',
		);
	});
});

suite('SCSS Hover', () => {
	test('nested specificity', () => {
		const assertSpecificity = (input: string, specificity: string, languageId = 'scss') => {
			const document = TextDocument.create(`test://test/test.${languageId}`, languageId, 0, input.replace('|', ''));
			const ls = languageId === 'less' ? getLESSLanguageService() : getSCSSLanguageService();
			const hover = ls.doHover(document, document.positionAt(input.indexOf('|')), ls.parseStylesheet(document));
			assert.strictEqual((<MarkedString[]>hover!.contents).at(-1), `[Selector Specificity](https://developer.mozilla.org/docs/Web/CSS/Specificity): ${specificity}`, input);
		};
		assertSpecificity('input { #id { |p { color: red; } } }', '(1, 0, 2)'); // #309
		assertSpecificity('input #id |p { color: red; }', '(1, 0, 2)');
		assertSpecificity('.a { > .|b {} }', '(0, 2, 0)');
		assertSpecificity('.a { &:h|over {} }', '(0, 2, 0)');
		assertSpecificity('.a { .b |& {} }', '(0, 2, 0)');
		assertSpecificity('.a { & + |& {} }', '(0, 2, 0)'); // each `&` counts
		assertSpecificity('.a { &-|b {} }', '(0, 1, 0)'); // suffix, still a single class
		assertSpecificity('.a, #b { .|c {} }', '(1, 1, 0)'); // most specific parent selector
		assertSpecificity('#x { .y { @media print { |p {} } } }', '(1, 1, 1)');
		assertSpecificity('.a { @at-root { .|b {} } }', '(0, 1, 0)');
		assertSpecificity('.a { @at-root (without: media) { .|b {} } }', '(0, 1, 0)');
		assertSpecificity('.a { @at-root .|b {} }', '(0, 1, 0)');
		assertSpecificity('.a { @at-root .b { .|c {} } }', '(0, 2, 0)');
		assertSpecificity('.a { @mixin m { .|b {} } }', '(0, 1, 0)');
		assertSpecificity('.a { @scope (.x) { .|b {} } }', '(0, 1, 0)'); // relative to `:where(:scope)`
		assertSpecificity('@scope (.x) { .a { .|b {} } }', '(0, 2, 0)');
		assertSpecificity('.a { &-|& {} }', '(0, 2, 0)', 'less');
	});

	test('@at-root', () => {
		assertHover(
			'.test { @|at-root { }',
			{
				contents: [],
			},
			'scss',
		);
	});
});
